<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.examples.com/wsdl/RuleBaseService.wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RuleBaseService" targetNamespace="http://www.examples.com/wsdl/RuleBaseService.wsdl">
   <message name="RuleBaseRequest">
      <part name="rating" type="xsd:integer" />
      <part name="loanAmount" type="xsd:integer" />
      <part name="loanDuration" type="xsd:integer" />
   </message>
   <message name="RuleBaseResponse">
      <part name="bankListJSON" type="xsd:string" />
   </message>
   <portType name="RuleBasePortType">
      <operation name="RuleBaseOperation">
         <input message="tns:RuleBaseRequest" />
         <output message="tns:RuleBaseResponse" />
      </operation>
   </portType>
   <binding name="RuleBaseBinding" type="tns:RuleBasePortType">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
      <operation name="RuleBaseOperation">
         <soap:operation soapAction="RuleBaseOperation" />
         <input>
            <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:rulebaseservice" use="encoded" />
         </input>
         <output>
            <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:rulebaseservice" use="encoded" />
         </output>
      </operation>
   </binding>
   <service name="RuleBaseService">
      <documentation>WSDL File for RuleBaseService</documentation>
      <port binding="tns:RuleBaseBinding" name="RuleBasePort">
         <soap:address location="http://localhost:8001/wsdl/" />
      </port>
   </service>
</definitions>
