apiVersion: v1
kind: Service
metadata:
  name: 1getcreditscore-lb
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: 1getcreditscore
