apiVersion: v1
kind: Service
metadata:
  name: getcreditscore-1-lb
spec:
  type: LoadBalancer
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: 1getcreditscore
