apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 0bank-1
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: 0bank-1
    spec:
     containers:
       - image: dolphinnews/0bank-1:siej33
         imagePullPolicy: Always
         name: 0bank-1
