apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 0rulebase
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: 0rulebase
    spec:
     containers:
       - image: dolphinnews/0rulebase:siej33
         imagePullPolicy: Always
         name: 0rulebase
         ports:
           - containerPort: 9000
