apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 1getcreditscore
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: 1getcreditscore
    spec:
     containers:
       - image: dolphinnews/1getcreditscore:dfie93
         imagePullPolicy: Always
         name: 1getcreditscore
         ports:
           - containerPort: 3001
