apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 3reciplist
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: 3reciplist
    spec:
     containers:
       - image: dolphinnews/3reciplist:dfie93
         imagePullPolicy: Always
         name: 3reciplist
