apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 4translator
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: 4translator
    spec:
     containers:
       - image: dolphinnews/4translator:dfie93
         imagePullPolicy: Always
         name: 4translator
